[features]
seeds = false
skip-lint = false
[programs.localnet]
chainlink_feed = "BjxRX7HBxAkJr1ty6sS53bqkL4kon28zSZgjTUKqyg8j"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/grajnikanth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
